on: [push]
name: Linyux_Deploy

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Entering in the wooden door'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Building Minecraft House'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/mc_mod
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mc_mod

        - name: 'Pressing save game OwO'
          uses: 'azure/aci-deploy@v1'
          with:
          
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: femboycrusaders
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/mc_mod
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: bigfattyfemboy
            azure-file-volume-account-key: Hp6YHHJAzgJbmdaYycSPqz9DfkSgULqoipo4vXShQdjqPlrS9G+VWy+96Oa0wN+Jsa4CrFa9s5vqQWuzLt6/Kw==
            azure-file-volume-account-name: femboybooty
            azure-file-volume-mount-path: /usr/src/mcserver/world
            azure-file-volume-share-name: acishare
            memory: 4
            cpu: 2
            ports: 25565
            location: 'west europe'
